insert into companies (id, deleted_at, name) values (1, null, 'Unexpected Larkspur');
insert into companies (id, deleted_at, name) values (2, null, 'California Mustard');
insert into companies (id, deleted_at, name) values (3, null, 'Skin Lichen');
insert into companies (id, deleted_at, name) values (4, null, 'Hartweg''s Spineflower');
insert into companies (id, deleted_at, name) values (5, null, 'Beggarslice');
insert into companies (id, deleted_at, name) values (6, null, 'Gregg''s Hawthorn');
insert into companies (id, deleted_at, name) values (7, null, 'Mt. Eddy Buckwheat');
insert into companies (id, deleted_at, name) values (8, null, 'Cuckoo Flower');
insert into companies (id, deleted_at, name) values (9, null, 'Carlott''s Wijkia Moss');
insert into companies (id, deleted_at, name) values (10, null, 'Kauai Wild Coffee');
insert into companies (id, deleted_at, name) values (11, null, 'Forked Wormwood');
insert into companies (id, deleted_at, name) values (12, null, 'Poeltinula Lichen');
insert into companies (id, deleted_at, name) values (13, null, 'Ditch Stonecrop');
insert into companies (id, deleted_at, name) values (14, null, 'Beard Lichen');
insert into companies (id, deleted_at, name) values (15, null, 'Ballhead Sandwort');
insert into companies (id, deleted_at, name) values (16, null, 'Yerba De Zanja');
insert into companies (id, deleted_at, name) values (17, null, 'Wild Guave');
insert into companies (id, deleted_at, name) values (18, null, 'Black Sweetwood');
insert into companies (id, deleted_at, name) values (19, null, 'Cottongrass');
insert into companies (id, deleted_at, name) values (20, null, 'Lotononis');
insert into companies (id, deleted_at, name) values (21, null, 'Mountain Nettle');
insert into companies (id, deleted_at, name) values (22, null, 'Nuttall''s Rayless Goldenrod');
insert into companies (id, deleted_at, name) values (23, null, 'Soft Milkpea');
insert into companies (id, deleted_at, name) values (24, null, 'Canarygrass');
insert into companies (id, deleted_at, name) values (25, null, 'Russian Wheatgrass');
insert into companies (id, deleted_at, name) values (26, null, 'Golden Saxifrage');
insert into companies (id, deleted_at, name) values (27, null, 'Camasey Almendre');
insert into companies (id, deleted_at, name) values (28, null, 'Sourthern Woodrush');
insert into companies (id, deleted_at, name) values (29, null, 'Nimblewill');
insert into companies (id, deleted_at, name) values (30, null, 'African Star Apple');
