insert into distributers (id, deleted_at, name) values (1, null, 'Kaibab Pussytoes');
insert into distributers (id, deleted_at, name) values (2, null, 'Front Range Beardtongue');
insert into distributers (id, deleted_at, name) values (3, null, 'San Benito Monardella');
insert into distributers (id, deleted_at, name) values (4, null, 'Swallow-wort');
insert into distributers (id, deleted_at, name) values (5, null, 'Mountain-avens');
insert into distributers (id, deleted_at, name) values (6, null, 'Roughleaf Yellow Loosestrife');
insert into distributers (id, deleted_at, name) values (7, null, 'Braunton''s Milkvetch');
insert into distributers (id, deleted_at, name) values (8, null, 'Poeltinula Lichen');
insert into distributers (id, deleted_at, name) values (9, null, 'Heermann''s Tarweed');
insert into distributers (id, deleted_at, name) values (10, null, 'Spurry Buckwheat');
insert into distributers (id, deleted_at, name) values (11, null, 'Threadleaf Sundew');
insert into distributers (id, deleted_at, name) values (12, null, 'Spurge');
insert into distributers (id, deleted_at, name) values (13, null, 'Cusick''s Shootingstar');
insert into distributers (id, deleted_at, name) values (14, null, 'Showy Fanpetals');
insert into distributers (id, deleted_at, name) values (15, null, 'Carolina Fanwort');
insert into distributers (id, deleted_at, name) values (16, null, 'Papaya');
insert into distributers (id, deleted_at, name) values (17, null, 'Crownvetch');
insert into distributers (id, deleted_at, name) values (18, null, 'Common Sandaster');
insert into distributers (id, deleted_at, name) values (19, null, 'Pauper Milkvetch');
insert into distributers (id, deleted_at, name) values (20, null, 'Fairywand');
insert into distributers (id, deleted_at, name) values (21, null, 'Western Bird''s-foot Trefoil');
insert into distributers (id, deleted_at, name) values (22, null, 'Sulphur-flower Buckwheat');
insert into distributers (id, deleted_at, name) values (23, null, 'Santa Barbara Island Buckwheat');
insert into distributers (id, deleted_at, name) values (24, null, 'Lost River Draba');
insert into distributers (id, deleted_at, name) values (25, null, 'Jacob''s Dotted Lichen');
insert into distributers (id, deleted_at, name) values (26, null, 'Orthodontium Moss');
insert into distributers (id, deleted_at, name) values (27, null, 'West Indian Tufted Airplant');
insert into distributers (id, deleted_at, name) values (28, null, 'Spreading Bladderpod');
insert into distributers (id, deleted_at, name) values (29, null, 'Pacific Dewberry');
insert into distributers (id, deleted_at, name) values (30, null, 'Rowell''s Groundcherry');
